#!/usr/bin/env bash
set -euo pipefail

: "${GCP_PROJECT_ID:?Set GCP_PROJECT_ID}"
: "${GCP_REGION:?Set GCP_REGION, e.g. europe-west1}"
: "${AR_REPOSITORY:?Set AR_REPOSITORY, e.g. trading}"
: "${CLOUD_RUN_SERVICE:?Set CLOUD_RUN_SERVICE, e.g. atlas-trading-api}"
: "${MODEL_BUCKET:?Set MODEL_BUCKET}"
: "${MODEL_STAGING_BUCKET:?Set MODEL_STAGING_BUCKET}"
: "${SERVICE_ACCOUNT:?Set SERVICE_ACCOUNT}"
: "${SECRET_DATABASE_VERSION:?Set SECRET_DATABASE_VERSION, e.g. 3}"
: "${SECRET_KEY_VERSION:?Set SECRET_KEY_VERSION, e.g. 7}"
: "${SECRET_TRON_XPUB_VERSION:?Set SECRET_TRON_XPUB_VERSION for the public TRON account xpub}"
: "${SECRET_APP_ENCRYPTION_VERSION:?Set SECRET_APP_ENCRYPTION_VERSION}"
: "${SECRET_REDIS_URL_VERSION:?Set SECRET_REDIS_URL_VERSION}"
: "${SUPABASE_URL:?Set SUPABASE_URL}"
: "${ADMIN_SUPABASE_USER_IDS:?Set ADMIN_SUPABASE_USER_IDS}"
: "${BACKUP_RECOVERY_URL:?Set BACKUP_RECOVERY_URL}"
: "${SECRET_TRONGRID_VERSION:?Set SECRET_TRONGRID_VERSION, e.g. 2}"
: "${SECRET_MODEL_SIGNING_PUBLIC_VERSION:?Set SECRET_MODEL_SIGNING_PUBLIC_VERSION}"
: "${SECRET_SUPABASE_ANON_KEY_VERSION:?Set SECRET_SUPABASE_ANON_KEY_VERSION}"
: "${SECRET_FUNDING_WEBHOOK_VERSION:?Set SECRET_FUNDING_WEBHOOK_VERSION}"
: "${FORWARDED_ALLOW_IPS:?Set FORWARDED_ALLOW_IPS to trusted proxy IP/CIDR; never *}"
: "${SECRET_GEMINI_API_KEY_VERSION:?Set SECRET_GEMINI_API_KEY_VERSION}"
SECRET_GROQ_API_KEY_VERSION="${SECRET_GROQ_API_KEY_VERSION:-}"

AI_SECRET_ARGS="GEMINI_API_KEY=atlas-gemini-api-key:${SECRET_GEMINI_API_KEY_VERSION}"
if [[ -n "$SECRET_GROQ_API_KEY_VERSION" ]]; then AI_SECRET_ARGS=",${AI_SECRET_ARGS},GROQ_API_KEY=atlas-groq-api-key:${SECRET_GROQ_API_KEY_VERSION}"; fi

IMAGE="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${AR_REPOSITORY}/${CLOUD_RUN_SERVICE}:$(git rev-parse --short HEAD 2>/dev/null || date +%Y%m%d%H%M%S)"
SA="${SERVICE_ACCOUNT}@${GCP_PROJECT_ID}.iam.gserviceaccount.com"

gcloud config set project "$GCP_PROJECT_ID"
gcloud builds submit --tag "$IMAGE" .

ENV_VARS="^@^ENVIRONMENT=production@PAPER_TRADING=true@LIVE_TRADING_ENABLED=false@BROKER_SANDBOX=true@DOCS_ENABLED=false@METRICS_REQUIRE_ADMIN=true@BACKGROUND_RECONCILIATION_ENABLED=false@PROCESS_ROLE=api@MODEL_DIR=/app/models@USDT_TRON_ENABLED=true@USDT_TRON_NETWORK=mainnet@USDT_TRONGRID_BASE_URL=https://api.trongrid.io@USDT_TRON_USDT_CONTRACT=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t@USDT_TRON_POLL_SECONDS=60@USDT_TRON_MIN_CONFIRMATIONS=19@FORWARDED_ALLOW_IPS=${FORWARDED_ALLOW_IPS}@SUPABASE_URL=${SUPABASE_URL}@ADMIN_SUPABASE_USER_IDS=${ADMIN_SUPABASE_USER_IDS}@BACKUP_RECOVERY_URL=${BACKUP_RECOVERY_URL}@ADMIN_TOTP_REQUIRED=true@DISTRIBUTED_RATE_LIMIT_REQUIRED=true@REQUIRE_BACKUP_RECOVERY_CONFIG=true@GEMINI_MODEL=gemini-2.5-flash@GEMINI_STRATEGY_MODEL=gemini-2.5-pro@GROQ_MODEL=openai/gpt-oss-20b@GROQ_STRATEGY_MODEL=openai/gpt-oss-20b@GROQ_MAX_COMPLETION_TOKENS=4096"

gcloud run deploy "$CLOUD_RUN_SERVICE" \
  --image "$IMAGE" \
  --region "$GCP_REGION" \
  --execution-environment gen2 \
  --service-account "$SA" \
  --port 8000 \
  --min-instances 1 \
  --max-instances 5 \
  --concurrency 40 \
  --cpu 2 \
  --memory 2Gi \
  --timeout 300 \
  --set-env-vars "$ENV_VARS" \
  --set-secrets "DATABASE_URL=atlas-database-url:${SECRET_DATABASE_VERSION},SECRET_KEY=atlas-secret-key:${SECRET_KEY_VERSION},APP_ENCRYPTION_KEY=atlas-app-encryption-key:${SECRET_APP_ENCRYPTION_VERSION},REDIS_URL=atlas-redis-url:${SECRET_REDIS_URL_VERSION},USDT_TRON_ACCOUNT_XPUB=atlas-usdt-tron-account-xpub:${SECRET_TRON_XPUB_VERSION},MODEL_SIGNING_PUBLIC_KEY=atlas-model-signing-public-key:${SECRET_MODEL_SIGNING_PUBLIC_VERSION},SUPABASE_ANON_KEY=atlas-supabase-anon-key:${SECRET_SUPABASE_ANON_KEY_VERSION},FUNDING_WEBHOOK_SECRET=atlas-funding-webhook-secret:${SECRET_FUNDING_WEBHOOK_VERSION},USDT_TRONGRID_API_KEY=atlas-trongrid-api-key:${SECRET_TRONGRID_VERSION}${AI_SECRET_ARGS}" \
  --add-volume "mount-path=/app/models,type=cloud-storage,bucket=$MODEL_BUCKET,readonly=true,mount-options=uid=10001;gid=10001" \
  --ingress internal-and-cloud-load-balancing \
  --allow-unauthenticated

gcloud run services describe "$CLOUD_RUN_SERVICE" --region "$GCP_REGION" --format='value(status.url)'
