#!/usr/bin/env bash
set -euo pipefail

: "${GCP_PROJECT_ID:?Set GCP_PROJECT_ID}"
: "${GCP_REGION:?Set GCP_REGION}"
: "${WORKER_POOL:?Set WORKER_POOL, e.g. atlas-trading-worker}"
: "${IMAGE:?Set IMAGE to the immutable Atlas image already built}"
: "${WORKER_SERVICE_ACCOUNT:?Set WORKER_SERVICE_ACCOUNT}"
: "${DATABASE_SECRET_REF:?Set DATABASE_SECRET_REF, e.g. atlas-database-url:3}"
: "${SECRET_REDIS_URL_REF:?Set SECRET_REDIS_URL_REF, e.g. atlas-redis-url:3}"
: "${SECRET_KEY_REF:?Set SECRET_KEY_REF}"
: "${SECRET_APP_ENCRYPTION_REF:?Set SECRET_APP_ENCRYPTION_REF}"
: "${SECRET_TRON_XPUB_REF:?Set SECRET_TRON_XPUB_REF}"
: "${SECRET_TRONGRID_REF:?Set SECRET_TRONGRID_REF}"
: "${SECRET_MODEL_SIGNING_PUBLIC_REF:?Set SECRET_MODEL_SIGNING_PUBLIC_REF}"
: "${SECRET_MODEL_SIGNING_PRIVATE_REF:?Set SECRET_MODEL_SIGNING_PRIVATE_REF}"
: "${SECRET_GEMINI_REF:?Set SECRET_GEMINI_REF}"
: "${MODEL_BUCKET:?Set MODEL_BUCKET}"
: "${MODEL_STAGING_BUCKET:?Set MODEL_STAGING_BUCKET}"

SA="${WORKER_SERVICE_ACCOUNT}@${GCP_PROJECT_ID}.iam.gserviceaccount.com"

gcloud config set project "$GCP_PROJECT_ID"
gcloud run worker-pools deploy "$WORKER_POOL" \
  --region "$GCP_REGION" \
  --image "$IMAGE" \
  --service-account "$SA" \
  --instances 1 \
  --cpu 2 \
  --memory 2Gi \
  --command python \
  --args=-m,app.worker \
  --set-env-vars "ENVIRONMENT=production,PROCESS_ROLE=worker,PAPER_TRADING=true,LIVE_TRADING_ENABLED=false,BROKER_SANDBOX=true,DOCS_ENABLED=false,MODEL_DIR=/app/models,MODEL_STAGING_DIR=/app/model-staging,USDT_TRON_ENABLED=true,USDT_TRON_NETWORK=mainnet,USDT_TRONGRID_BASE_URL=https://api.trongrid.io,USDT_TRON_USDT_CONTRACT=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t,USDT_TRON_POLL_SECONDS=60,USDT_TRON_MIN_CONFIRMATIONS=19,DISTRIBUTED_RATE_LIMIT_REQUIRED=true,EXTERNAL_SECURITY_AUDIT_ENABLED=true,EXTERNAL_SECURITY_AUDIT_REQUIRED=true,GEMINI_MODEL=gemini-2.5-flash,GEMINI_STRATEGY_MODEL=gemini-2.5-pro" \
  --set-secrets "DATABASE_URL=$DATABASE_SECRET_REF,SECRET_KEY=$SECRET_KEY_REF,APP_ENCRYPTION_KEY=$SECRET_APP_ENCRYPTION_REF,REDIS_URL=$SECRET_REDIS_URL_REF,USDT_TRON_ACCOUNT_XPUB=$SECRET_TRON_XPUB_REF,USDT_TRONGRID_API_KEY=$SECRET_TRONGRID_REF,MODEL_SIGNING_PUBLIC_KEY=$SECRET_MODEL_SIGNING_PUBLIC_REF,MODEL_SIGNING_PRIVATE_KEY=$SECRET_MODEL_SIGNING_PRIVATE_REF,GEMINI_API_KEY=$SECRET_GEMINI_REF" \
  --add-volume "mount-path=/app/models,type=cloud-storage,bucket=$MODEL_BUCKET,readonly=false,mount-options=uid=10001;gid=10001" \
  --add-volume "mount-path=/app/model-staging,type=cloud-storage,bucket=$MODEL_STAGING_BUCKET,readonly=false,mount-options=uid=10001;gid=10001"
